# -*- coding: utf-8 -*-
"""Data Mining_Naive Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1vr_zNEUsBW6cjJUB0PiAIkwa5FhcKn
"""

# Colab-ready: Naive Bayes pipeline for loan approval
!pip install scikit-learn joblib --quiet

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib
import os

# 1) Upload your CSV to Colab (or mount Drive) and set file_path accordingly
file_path = "/content/loan_approval.csv"  # change if you upload somewhere else
df = pd.read_csv(file_path)
print("Columns and dtypes:\n", df.dtypes)
print("\nSample rows:\n", df.head())

# 2) Auto-detect target column (common variants). If none found, uses last column.
cols = df.columns.astype(str).tolist()
target_candidates = [c for c in cols if ('loan' in c.lower() and ('approve' in c.lower() or 'approval' in c.lower())) or c.lower() in ['approved','approval','loan_approval','loanapproved']]
if len(target_candidates) == 0:
    # Also accept boolean-like columns
    bool_like = [c for c in cols if df[c].dropna().isin([True, False, 'TRUE','FALSE','Yes','No',1,0]).all() if df[c].dropna().shape[0] > 0]
    target_candidates = bool_like
if len(target_candidates) == 0:
    target_col = cols[-1]
    print(f"No obvious 'loan approval' column detected — using last column as target: '{target_col}'")
else:
    target_col = target_candidates[0]
    print(f"Detected target column: '{target_col}'")

# 3) Normalize/mapping target to 0/1
def map_to_binary(x):
    if pd.isna(x): return np.nan
    if isinstance(x, (bool, np.bool_)): return int(x)
    s = str(x).strip().lower()
    if s in ['true','t','yes','y','1','approved','approve']: return 1
    if s in ['false','f','no','n','0','denied','reject','rejected']: return 0
    try:
        v = float(s)
        return 1 if v==1 else 0 if v==0 else np.nan
    except:
        return np.nan

df['__target__'] = df[target_col].map(map_to_binary)
df = df.dropna(subset=['__target__'])
df['__target__'] = df['__target__'].astype(int)

# 4) Drop identifier-like high-cardinality string columns (e.g., name)
n_rows = df.shape[0]
object_cols = df.select_dtypes(include=['object']).columns.tolist()
id_like = [c for c in object_cols if df[c].nunique() / n_rows > 0.5]
if id_like:
    print("Dropping identifier-like columns:", id_like)
    df = df.drop(columns=id_like)

# 5) Prepare feature lists
target = '__target__'
feature_cols = [c for c in df.columns if c != target and c != target_col]
numeric_cols = df[feature_cols].select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = [c for c in feature_cols if c not in numeric_cols]

print("Numeric cols:", numeric_cols)
print("Categorical cols:", categorical_cols)

# 6) Build pipeline
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_cols),
    ('cat', categorical_transformer, categorical_cols)
], remainder='drop')

X = df[feature_cols]
y = df[target]

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('clf', GaussianNB())
])

# 7) Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Target Training data shape",y_train.shape)
print("Target Testing data shape",y_test.shape)

model.fit(X_train, y_train)

# 8) Train the model
model.fit(X_train, y_train)
print("Model training complete.")

# 9) Evaluate the model
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 10) Visual Representation:
import matplotlib.pyplot as plt
import seaborn as sns

# Get the confusion matrix from the previous output
cm = confusion_matrix(y_test, y_pred)

# Plot the confusion matrix as a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No Approval', 'Predicted Approval'],
            yticklabels=['Actual No Approval', 'Actual Approval'])
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.title('Confusion Matrix')
plt.show()

# 11) Cross-validation (if enough rows)
if len(df) >= 10:
    cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
    print("5-fold CV accuracies:", cv_scores)

# 12) Save the model
out_path = "/content/naive_bayes_loan_model.joblib"
joblib.dump(model, out_path)
print("Saved model to:", out_path)