# -*- coding: utf-8 -*-
"""Deep Learning--ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xX5Hqz6z4vGYojnbF8cf_MunLsRW6lA
"""

from torchvision import datasets, transforms

# Define a transform to convert images to tensors
transform = transforms.Compose([transforms.ToTensor()])

# Download and load the training data
train_data = datasets.MNIST(root='./data', train=True, download=True, transform=transform)

# Download and load the test data
test_data = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

print(f"Training data size: {len(train_data)}")

from IPython.testing import test
test_data_size = len(test_data)
print(test_data_size)

test_data.__getitem__(0)

image, label = test_data[0]

print(f"uShape of image tensor: {image.shape}")
print(f"Data type of image tensor: {image.dtype}")
print(f"Min pixel value: {image.min().item()}")
print(f"Max pixel value: {image.max().item()}")
print(f"Label of first item: {label}")
print("Labels in MNIST dataset are typically integers from 0 to 9.")

import matplotlib.pyplot as plt

# Get the first image and its label from the test dataset
image, label = test_data[0]

# Remove the channel dimension for displaying (if it's a single-channel image)
# and convert to a NumPy array
image_np = image.squeeze().numpy()

# Display the image
plt.imshow(image_np, cmap='grey')
plt.title(f"Label: {label}")
plt.axis('off') # Hide axes
plt.show()

import matplotlib.pyplot as plt
import torch

# Get all labels from the test dataset
labels = test_data.targets

# Count the occurrences of each label
label_counts = torch.bincount(labels)

# Create a list of digit labels (0-9)
digits = range(len(label_counts))

# Plot the distribution
plt.figure(figsize=(10, 6))
plt.bar(digits, label_counts.numpy(), tick_label=digits, color='skyblue')
plt.xlabel('Digit')
plt.ylabel('Number of Occurrences')
plt.title('Distribution of Labels in MNIST Test Dataset')
plt.xticks(digits)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""torch and sklearn (for generating dummy data) installed:"""

pip install torch scikit-learn

"""To help you solve Artificial Neural Network (ANN) problems, I have designed a step-by-step tutorial using PyTorch.

This tutorial builds a standard Feedforward Neural Network (a common type of ANN) to solve a Binary Classification problem (classifying data into two groups, like "Yes/No" or "Spam/Not Spam").

Prerequisites
You will need torch and sklearn (for generating dummy data) installed:

Bash

pip install torch scikit-learn
Step 1: Data Preparation
First, we generate synthetic data. In a real-world scenario, you would load a CSV or image dataset here. We use DataLoader to handle batching, which is crucial for training ANNs efficiently.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split

# 1. Generate synthetic data (concentric circles)
# This creates a non-linear problem that requires a Neural Network to solve
X, y = make_circles(n_samples=1000, noise=0.03, random_state=42)

# 2. Convert to PyTorch Tensors
# PyTorch works with Tensors, not NumPy arrays.
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).reshape(-1, 1) # Reshape to (N, 1)

# 3. Split into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Create DataLoaders
# DataLoaders allow us to iterate through data in "batches" (e.g., 32 samples at a time)
dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(dataset, batch_size=32, shuffle=True)

"""Key Concepts:

Tensors: The fundamental data structure in PyTorch (similar to NumPy arrays but GPU-compatible).

Batching: Training on small subsets (batches) prevents memory overload and often helps the model converge faster.

Step 2: Define the ANN Architecture
We define the network by subclassing nn.Module. We need to define the layers in __init__ and the flow of data in forward
"""

class SimpleANN(nn.Module):
    def __init__(self):
        super(SimpleANN, self).__init__()
        # Layer 1: Takes 2 input features (x, y coordinates), outputs 10 hidden neurons
        self.layer_1 = nn.Linear(in_features=2, out_features=10)

        # Layer 2: Takes 10 hidden neurons, outputs 10 more (adding depth)
        self.layer_2 = nn.Linear(in_features=10, out_features=10)

        # Output Layer: Takes 10 features, outputs 1 single value (probability)
        self.output = nn.Linear(in_features=10, out_features=1)

        # Activation Function: ReLU (Rectified Linear Unit) introduces non-linearity
        self.relu = nn.ReLU()

        # Sigmoid: Squashes output between 0 and 1 for binary classification
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Pass input through layer 1 -> Activation -> Layer 2 -> Activation -> Output
        x = self.relu(self.layer_1(x))
        x = self.relu(self.layer_2(x))
        x = self.sigmoid(self.output(x))
        return x

# Initialize the model
model = SimpleANN()
print(model)

"""Key Concepts:nn.Linear: A fully connected layer that applies a linear transformation ($y = xA^T + b$).nn.ReLU: An activation function that allows the network to learn complex patterns. Without it, the network would just be a linear regression.nn.Sigmoid: Converts the final "raw" number into a probability (0.0 to 1.0).

Step 3: Loss Function & Optimizer
We need a metric to measure error (Loss) and a way to update the model to reduce that error (Optimizer).
"""

# Loss Function: Binary Cross Entropy Loss (standard for binary classification)
criterion = nn.BCELoss()

# Optimizer: Stochastic Gradient Descent (SGD)
# lr=0.1 is the "learning rate" - how big of a step we take to correct errors
optimizer = optim.SGD(model.parameters(), lr=0.1)

"""Step 4: The Training Loop
This is the engine of the process. We loop through the data multiple times (epochs).
"""

epochs = 100

for epoch in range(epochs):
    for batch_X, batch_y in train_loader:
        # A. Forward Pass: Compute prediction
        y_pred = model(batch_X)

        # B. Calculate Loss: How wrong was the prediction?
        loss = criterion(y_pred, batch_y)

        # C. Optimizer Zero Grad: Clear old gradients from previous step
        optimizer.zero_grad()

        # D. Backward Pass (Backpropagation): Calculate gradient of loss w.r.t parameters
        loss.backward()

        # E. Step: Update model parameters based on gradients
        optimizer.step()

    # Print loss every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1} | Loss: {loss.item():.5f}")

"""Explanation of the Loop:

Forward: The model guesses.

Loss: We check how wrong the guess is.

Zero Grad: We reset the "correction manual" (gradients) so we don't accidentally mix updates from previous batches.

Backward: We calculate exactly how much each weight contributed to the error.

Step: We nudge the weights in the opposite direction of the error.

Step 5: Evaluation
Finally, we test the model on data it hasn't seen before to check for accuracy.
"""

# Turn off gradient calculation for evaluation (saves memory/speed)
model.eval()
with torch.no_grad():
    # Make predictions on the test set
    test_preds = model(X_test)

    # Convert probabilities to 0 or 1 (Decision Boundary: 0.5)
    predicted_labels = (test_preds >= 0.5).float()

    # Calculate accuracy
    correct = (predicted_labels == y_test).sum().item()
    accuracy = correct / len(y_test)

    print(f"\nTest Accuracy: {accuracy * 100:.2f}%")

"""Summary of Steps for Solving ANN Problems
Dataset: Ensure data is numerical and converted to torch.Tensor.

Model: Subclass nn.Module and stack nn.Linear layers with non-linear activations (like ReLU).

Loss: Use BCELoss for binary classification or MSELoss for regression.

Optimization: Use SGD or Adam to update weights.

Loop: Repeat Forward -> Loss -> Backward -> Step
"""

import torch
import torch.nn as nn
import torch.optim as optim

# 1. DATA
X = torch.tensor([[2.0, 1.0], [9.0, 8.0], [3.0, 2.0], [8.0, 7.0]])
y = torch.tensor([[0.0], [1.0], [0.0], [1.0]])

# 2. MODEL
model = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 1),
    nn.Sigmoid()
)

# 3. LOSS & OPTIMIZER
loss_fn = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# 4. TRAINING LOOP (The New Part!)
print("--- Starting Training ---")

for epoch in range(1000):
    # A. GUESS
    predictions = model(X)

    # B. CHECK ERROR
    loss = loss_fn(predictions, y)

    # C. FIX THE MODEL (The Magic 3 Steps)
    optimizer.zero_grad()   # 1. Clear previous calculations
    loss.backward()         # 2. Calculate necessary corrections (gradients)
    optimizer.step()        # 3. Update weights

    # Print progress every 100 rounds
    if (epoch + 1) % 100 == 0:
        print(f"Round {epoch+1}: Error is {loss.item():.4f}")

# 5. FINAL TEST
print("\n--- Final Test ---")
test_data = torch.tensor([[2.0, 1.0]]) # A student who studied little
result = model(test_data)
print(f"Prediction for input [2.0, 1.0]: {result.item():.4f}")
print("Note: Closer to 0 means Fail, Closer to 1 means Pass")

"""The "Magic 3" Steps Explained
This part usually confuses beginners, so let's use a simple analogy: Archery.

Imagine you are shooting an arrow at a target.

optimizer.zero_grad() (Clear the mind):

Before you take a new shot, you must forget the wind conditions of the last shot. If you don't reset, you'll be correcting for wind that isn't there anymore.

Technical: PyTorch accumulates gradients. If we don't zero them out, the new calculation gets added to the old one, creating a mess.

loss.backward() (Analyze the miss):

You shoot and miss by 5 inches to the left. You analyze: "My arm was too low, and my grip was too tight."

Technical: This calculates the Gradient. It looks at the error and traces it backward through the network to find out which weight contributed to the mistake.

optimizer.step() (Adjust the aim):

You adjust your stance. You aim slightly to the right for the next shot.

Technical: This updates the numbers (weights) inside the model using the Learning Rate.

The Result
When you run this, you will see the error drop:

Round 100: Error is 0.60 (Still confused)

Round 500: Error is 0.35 (Getting better)

Round 1000: Error is 0.04 (Almost perfect!)

And the final prediction for [2.0, 1.0] (Low study, Low sleep) should be very close to 0.0 (Fail).

You have just built and trained your first Neural Network from scratch!
"""